###############################################################################.
# MODULE: download_data_btns_mod ---- 
# creates a menu button that when clicked on, provides 3 different options for downloading data (csv, rds or json)
# it then downloads the data in the format the user has selected
# there is also an optional arguments in the server function to specify which columns of data to include in the download
# by default all columns are included unless you use pass a vector of column names to the selectedColumns argument
# note this module can be nested inside other modules where download buttons are required.


##############################################################################.
# example usage - repex of how this module works can be generated by running 
# the functions declared above then uncommenting the code below.
##############################################################################.
# library(shiny)
# library(shinyWidgets)
# library(jsonlite)
# library(dplyr)
# 
# dummy_data <- data.frame(fruit = c("apples", "oranges", "pears"),
#                          colour = c("green", "orange", "green"))
# 
# 
# ui <- fluidPage(
#   h1("Download reactive data"),
#   selectInput(inputId = "colour_filter", label = "select fruit colour", choices = unique(dummy_data$colour)),
#   download_data_btns_ui("df_download"),
#   download_data_btns_ui("dt_download")
#   )
# 
# server <- function(input, output, session) {
# 
# 
#   df_data <- reactive({
#     dummy_data |>
#       filter(colour == input$colour_filter)
#   })
#   
#   
#   dt_data <- reactive({
#     dt <- setDT(dummy_data)
#     dt <- dt[colour == input$colour_filter]
#     dt
#   })
# 
# 
#   download_data_btns_server("dt_download", data = dt_data, selected_columns = c("fruit"))
#   download_data_btns_server("df_download", data = df_data)
# }
# 
# 
# shinyApp(ui, server)
